	<div id="overall">

		<div id="side1">
		   Welcome:::
		   <a href=".?pg=logout">
			Log out
		   </a>
		</div>
		<div id="side2">
			<p id="adm-menu">ADMINISTRATOR MENU</p>
			<ul>
				<li>Pre-Election Setting
					<ul>
						<li><a href=".?pg=school">School</a></li>
						<li><a href=".?pg=faculty">Faculty</a></li>
						<li><a href=".?pg=department">Department</a></li>
					</ul>
				</li>
				<li><a href=".?pg=candidate">Manage Candidate</a></li>
				<li>Set-Up
					<ul>
						<li><a href=".?pg=election">Election Set-Up</a></li>
						<li><a href=".?pg=pins">Generate Pins</a></li>
					</ul>
				</li>
				<li><a href=".?pg=report">Election Report</a></li>
			</ul>
		</div>
			<div id="mid_1">
		</div>
	
	</div>
